-- Conecte-se ao banco M3Gestor antes de rodar

-- Tabela: clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(255) NOT NULL,
    endereco        VARCHAR(255),
    telefone        VARCHAR(50),
    email           VARCHAR(255),
    documento       VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_clientes_nome ON public.clientes (nome);

-- Tabela: quotes
CREATE TABLE IF NOT EXISTS public.quotes (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    client_id       INTEGER REFERENCES public.clientes(id) ON UPDATE CASCADE ON DELETE SET NULL,
    client_name     VARCHAR(255),
    date            DATE NOT NULL,
    shipping_value  DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_value     DOUBLE PRECISION NOT NULL DEFAULT 0,
    discount        DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (discount >= 0 AND discount <= 100),
    complemento     TEXT
);

CREATE INDEX IF NOT EXISTS idx_quotes_name ON public.quotes (name);
CREATE INDEX IF NOT EXISTS idx_quotes_date_id ON public.quotes (date DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_quotes_client_id ON public.quotes (client_id);

-- Tabela: quote_items
CREATE TABLE IF NOT EXISTS public.quote_items (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id    INTEGER NOT NULL REFERENCES public.quotes(id) ON UPDATE CASCADE ON DELETE CASCADE,
    quantity    INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    width       DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (width >= 0),
    height      DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (height >= 0),
    length      DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (length >= 0),
    unit_value  DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (unit_value >= 0),
    total       DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_quote_items_quote_id ON public.quote_items (quote_id);
CREATE INDEX IF NOT EXISTS idx_quote_items_id ON public.quote_items (id);